name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: hydren-dev
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Check if Docker image exists
      id: check_image
      run: |
        if ! docker pull ghcr.io/hydren-dev/daemon:latest; then
          echo "Image not found, proceeding to build."
          echo "image_exists=false" >> $GITHUB_ENV
        else
          echo "Image exists."
          echo "image_exists=true" >> $GITHUB_ENV
        fi

    - name: Build Docker image if not exists
      if: env.image_exists == 'false'
      run: |
        docker build -t ghcr.io/hydren-dev/daemon:latest .
        echo "Image built successfully."

    - name: Push Docker image to GHCR
      if: env.image_exists == 'false'
      run: |
        docker push ghcr.io/hydren-dev/daemon:latest
        echo "Image pushed to GHCR."

    - name: Verify Docker image
      run: |
        docker images
